### ISSUE TITLE
GTAVCS.PCSX2F.Project2DFX save disks and red balloons disappear, black screen when trying to change clothes

### ISSUE THREAD

**Issue by NightmanCometh96** [ThirteenAG/III.VC.SA.IV.Project2DFX#47]
I'm not sure what the cause is, but after playing the game for a while with the Project2DFX plugin (the exact timing is random, but it always seems to happen eventually), the red balloons and save icons around the map disappear (the actual disks inside your safehouses, not the ones on the radar). If you remember where the disk is, it's still possible to save, though; so it seems like they're still there, but just invisible. However, red balloons seem to be missing entirely, because trying to shoot where one would have been doesn't register as a "popped balloon".

The bigger problem happens if you try to change your clothes after the disks disappear. The game ends up hanging on a black screen.

These issues go away if you load a save, but they will eventually crop up again. I assume it's a problem with 2DFX, since I've tested the game for a few lengthy sessions with only the Widescreen Fixes plugin installed, and never had any of these issues with it.

**Comment by ThirteenAG** [comment]
Probably the same issue that makes crates disappear in one of the missions. Unfortunately I don't know how to fix it, our tests indicated that it's related to increased corona limit, which I also use in psp version and it works there. I checked the code multiple times and no clue what goes wrong.

**Comment by ThirteenAG** [comment]
@NightmanCometh96 good news, looks like @ermaccer figured it out!

![image](https://github.com/ThirteenAG/III.VC.SA.IV.Project2DFX/assets/4904157/1f22fdc2-5ab7-4f46-8920-9264d5619364)

Try this attached version:
[GTAVCS.PCSX2F.Project2DFX.zip](https://github.com/ThirteenAG/III.VC.SA.IV.Project2DFX/files/11657805/GTAVCS.PCSX2F.Project2DFX.zip)

**Comment by LtFrankDrebin** [comment]
I can confirm that the issue still exists even on the latest version of the mod (10 October), and the June version by ermaccer didn't really help me with disappearing red balloons either. I'm sure that Project2DFX is the culprit because as soon I uninstall it, the missing balloons are displayed again. I use the correct version of the game (SLUS-21590).

Not all balloons are affected by this glitch, though. In my tests I used balloons # 76, 77, 78 from [this video](https://www.youtube.com/watch?v=7B26rLrkvZU&t=2141s&ab_channel=GTASeriesVideos). The balloon # 77 isn't shown on the latest version (10 October), but reappears if I install ermaccer's edited file. However, even with ermaccer's edits, the balloons # 76 & 78 remain missing until I delete Project2DFX completely. So the version linked above seems to only fix the bug with the mission Boomshine Blowout, but the glitched balloons are still present.

**Comment by ThirteenAG** [comment]
Yes, it's caused by increased corona limit, for some reason works in psp version, but problematic in ps2 version. I'm out of ideas tbh.
I could try implementing a custom corona renderer, like in GTA SA version, maybe that will help.

**Comment by ThirteenAG** [comment]
@LtFrankDrebin may I ask you to test this version and check if the issue is still present?
[GTAVCS.PCSX2F.Project2DFX.zip](https://github.com/ThirteenAG/III.VC.SA.IV.Project2DFX/files/13463339/GTAVCS.PCSX2F.Project2DFX.zip)

It has corona limit removed and a different way to render coronas, which is very buggy right now, so expect coronas turn to rectangles and maybe other rendering issues, but the important part is to check whether or not the objects bug is still there.

**Comment by ThirteenAG** [comment]
Nevermind that, I've made corona rendering without corona limit adjuster, so pretty sure all these issues should be resolved now.

**Comment by LtFrankDrebin** [comment]
Thank you for updating the mod, ThirteenAG. The balloons I mentioned in my message above are now rendered correctly.

**Comment by ThirteenAG** [comment]
That's good to hear. I might update psp version as well later, since this code should give better performance.
